<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
          <div class="main-navbar">
            <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
              <a class="navbar-brand w-100 mr-0" href="#" style="line-height: 25px;">
                <div class="d-table m-auto">
                  <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 30px;" src="../images/logo.jpg" alt="Vetfront Animal Wellness Center">
                  <span class="d-none d-md-inline ml-1">Vetfront CMS</span>
                </div>
              </a>
              <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
              </a>
            </nav>
          </div>
          <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
            <div class="input-group input-group-seamless ml-3">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="fas fa-search"></i>
                </div>
              </div>
              <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> </div>
          </form>
          <div class="nav-wrapper">
            <ul class="nav flex-column">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                  <i class="material-icons">dashboard</i>
                  <span>Dashboard</span>
                </a>
				<div class="dropdown-menu dropdown-menu-small">
                  <a class="dropdown-item " href="dashboard.php">Sales Dashboard</a>
                  <a class="dropdown-item " href="#">Clinic Dashboard</a>
                </div>
              </li>
			  <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                  <i class="material-icons">pets</i>
                  <span>Veterinary</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
                  <a class="dropdown-item " href="#">New Patient</a>
                  <a class="dropdown-item " href="#">Manage Patients</a>
                </div>
              </li>
			  <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                  <i class="material-icons">payment</i>
                  <span>Transactions</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
                  <a class="dropdown-item " href="transaction.php">New Transaction</a>
                  <a class="dropdown-item " href="viewTransactions.php">Manage Transactions</a>
				  <a class="dropdown-item " href="addExpense.php">Add Expense</a>
				  <a class="dropdown-item " href="manageExpenses.php">Manage Expense</a>
                </div>
              </li>
			  <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                  <i class="material-icons">store</i>
                  <span>Products</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
                  <a class="dropdown-item " href="addProduct.php">Add Products</a>
                  <a class="dropdown-item " href="products.php">Manage Products</a>
				  <a class="dropdown-item " href="manageCategories.php">Manage Categories</a>
                </div>
              </li>
			  <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                  <i class="material-icons">store</i>
                  <span>Services</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
                  <a class="dropdown-item " href="createService.php">Create Service</a>
                  <a class="dropdown-item " href="manageServices.php">Manage Services</a>
                </div>
              </li>
			   <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                  <i class="material-icons">store</i>
                  <span>Suppliers</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
				  <a class="dropdown-item " href="#">Create Order</a>
                  <a class="dropdown-item " href="#">Add Supplier</a>
                  <a class="dropdown-item " href="#">Manage Suppliers</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="dailyRep.php">
                  <i class="material-icons">trending_up</i>
                  <span>Reports</span>
                </a>
              </li>
			  <li class="nav-item">
                <a class="nav-link " href="#">
                  <i class="material-icons">settings_applications</i>
                  <span>Settings</span>
                </a>
              </li>
            </ul>
          </div>
        </aside>